name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Enable corepack
      run: corepack enable
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    
    - name: Build
      run: pnpm install && pnpm build
        
    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.FTP_PORT }}
        local_path: './dist/*'
        remote_path: ${{ secrets.REMOTE_PATH }}
        sftp_only: true
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
